<?php 
/**
 * @file ViewFile for Book
 * 
 * Available variables
 */
$title   = $this->title;   // Title of the book
$id      = $this->id;      // The id of the book
$content = $this->content; // The content of the book
$author  = $this->author;  // The Author names
$comment = $this->comment; // Comment for the book
$toc     = $this->toc;
print "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../css/sys/labsys_epub_theme.css" />
<title><?php print $title ?></title>
</head>
<body>
<div id='titlepage' class='pageBreakAfter'>
    <h1 id='<?php print $id ?>' class='part-title'><?php print $title?></h1>
    <hr/>
    <h3 class='author'> <?php print $author ?> </h3>
    <div><?php print $comment ?></div>
</div>
<div class='pageBreakAfter'>
    <h3 id='toc'>Table Of contents</h3>
    <?php print $toc ?>
</div>
<?php print $content ?> 
</body></html>